apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - app-deployment.yaml
  - app-service.yaml
  - insecure-runtime-pod.yaml
  - runtime-attacker-pod.yaml
  - rbac-overprivileged.yaml