apiVersion: v1
kind: ServiceAccount
metadata:
  name: overprivileged-sa
  namespace: baseline
  labels:
    environment: baseline
    security-profile: weak
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: overprivileged-role
  namespace: baseline
  labels:
    environment: baseline
    security-profile: weak
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: overprivileged-rolebinding
  namespace: baseline
  labels:
    environment: baseline
    security-profile: weak
subjects:
  - kind: ServiceAccount
    name: overprivileged-sa
    namespace: baseline
roleRef:
  kind: Role
  name: overprivileged-role
  apiGroup: rbac.authorization.k8s.io