apiVersion: batch/v1
kind: Job
metadata:
  name: runtime-attacker
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: attacker
        image: alpine:latest
        command:
        - sh
        - -c
        - sleep 30