apiVersion: v1
kind: Pod
metadata:
  name: runtime-attacker
  namespace: baseline
  labels:
    app: runtime-attacker
    environment: baseline
    security-profile: weak
spec:
  restartPolicy: Never
  containers:
  - name: attacker
    image: alpine:latest
    command: ["sh", "-c", "sleep 3600"]
    securityContext:
      runAsUser: 0
      allowPrivilegeEscalation: true