apiVersion: v1
kind: Pod
metadata:
  name: allowed-web
  namespace: hardened
spec:
  restartPolicy: Never
  containers:
    - name: curl
      image: curlimages/curl:8.8.0
      command:
        - sh
        - -c
        - |
          curl http://hardened-nginx.hardened.svc.cluster.local