apiVersion: v1
kind: Pod
metadata:
  name: allowed-dns
  namespace: hardened
spec:
  restartPolicy: Never
  containers:
    - name: nslookup
      image: busybox:1.36
      command:
        - sh
        - -c
        - |
          nslookup kubernetes.default.svc.cluster.local