apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - allow-dns.yaml
  - allow-hardened-service.yaml
  - allow-report-server.yaml
  - deny-external-egress.yaml
  - deny-cross-namespace.yaml
  - deny-kube-api.yaml
  - deny-database.yaml
  - sa.yaml
  