apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - allow-dns-and-internet.yaml
  - deny-cross-namespace-ingress.yaml
  - deny-internet-egress.yaml
  - isolated-app-service.yaml

  