apiVersion: v1
kind: Namespace
metadata:
  name: isolated-target
  labels:
    ns-type: restricted-target
---
apiVersion: v1
kind: Pod
metadata:
  name: isolated-app
  namespace: isolated-target
  labels:
    app: target-service
spec:
  restartPolicy: Never
  securityContext:
    runAsNonRoot: true
    runAsUser: 101
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: web
      image: nginxinc/nginx-unprivileged:alpine
      ports:
        - containerPort: 8080
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop:
            - ALL
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi
      volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: cache
          mountPath: /var/cache/nginx
        - name: run
          mountPath: /var/run
  volumes:
    - name: tmp
      emptyDir: {}
    - name: cache
      emptyDir: {}
    - name: run
      emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: isolated-service
  namespace: isolated-target
spec:
  selector:
    app: target-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080