apiVersion: v1
kind: Pod
metadata:
  name: benign-http-server
  namespace: hardened
  labels:
    app: benign-http-server
spec:
  serviceAccount: benign-sa
  restartPolicy: Never
  securityContext:
    seccompProfile:
      type: RuntimeDefault
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
  containers:
  - name: http-server
    image: python:3.12-alpine
    command: ["python3", "-m", "http.server", "8080"]
    ports:
    - containerPort: 8080
      name: http
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL

    resources:
      requests:
        cpu: 100m
        memory: 64Mi

      limits:
        cpu: 200m
        memory: 128Mi