apiVersion: v1
kind: Pod
metadata:
  name: benign-nginx
  namespace: hardened
  labels:
    app: benign-nginx
spec:
  serviceAccount: benign-sa
  restartPolicy: Never
  securityContext:
    seccompProfile:
      type: RuntimeDefault
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
  containers:
  - name: nginx
    image: nginx:1.27-alpine
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL

    resources:
      requests:
        cpu: 100m
        memory: 64Mi

      limits:
        cpu: 200m
        memory: 128Mi
    volumeMounts:
    - name: nginx-cache
      mountPath: /var/cache/nginx
    - name: nginx-run
      mountPath: /var/run
  volumes:
  - name: nginx-cache
    emptyDir: {}
  - name: nginx-run
    emptyDir: {}