apiVersion: v1
kind: Pod
metadata:
  name: benign-internal-http
  namespace: hardened
  labels:
    app: benign-internal-http
    security: runtime-test
    msef.test: benign
spec:
  restartPolicy: Never

  serviceAccountName: hardened-app-sa

  automountServiceAccountToken: false

  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

  containers:
  - name: attack
    image: curlimages/curl
    command:
      - curl
    args:
      - http://kubernetes.default.svc

    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000

      capabilities:
        drop:
          - ALL

    resources:
      requests:
        cpu: 50m
        memory: 64Mi

      limits:
        cpu: 100m
        memory: 128Mi