apiVersion: v1
kind: Pod
metadata:
  name: benign-internal-http
  namespace: hardened
  labels:
    app: benign-internal-http
    security: runtime-test
spec:
  restartPolicy: Never

  serviceAccountName: hardened-app-sa

  automountServiceAccountToken: false

  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

  containers:
  - name: attack

    image: busybox:1.36

    command:
      - sh
      - -c
      - |
        echo "[+] Performing standard internal health check..."
        nc -z -w 2 10.96.0.10 53 || true
        sleep 5

    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000

      capabilities:
        drop:
          - ALL

    resources:
      requests:
        cpu: 50m
        memory: 64Mi

      limits:
        cpu: 100m
        memory: 128Mi