apiVersion: v1
kind: ServiceAccount
metadata:
  name: benign-app-sa
  namespace: baseline
---
apiVersion: v1
kind: Pod
metadata:
  name: benign-serviceaccount
  namespace: baseline
  labels:
    app: benign-serviceaccount
spec:
  restartPolicy: Never
  serviceAccountName: benign-app-sa
  automountServiceAccountToken: true
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: sa-checker
    image: busybox:1.36
    command: ["sh", "-c", "ls -l /var/run/secrets/kubernetes.io/serviceaccount && sleep 5"]
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop: ["ALL"]