apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-api-token
  namespace: hardened
spec:
  encryptedData:
    api-key: AgA3x42B...# [Truncated encrypted string from kubeseal CLI]
  template:
    metadata:
      name: app-api-token
      namespace: hardened
    type: Opaque