apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - cert-manager/application.yaml
  - gatekeeper/application.yaml
  - kyverno/application.yaml
  - falco/application.yaml
  - falco-side-kick/application.yaml
  - security-policy.yaml
  - external-secrets/application.yaml
  - eck/application.yaml
  - elasticsearch/application.yaml
  - kafka/kafka-resources/application.yaml
  - kafka/strimzi-kafka/application.yaml
  - istio/istiod/application.yaml
  - istio/istio-base/application.yaml
  - istio/istio-ingress/application.yaml
  - sealedsecret/application.yaml
  - monitoring/application.yaml
  - gateway/application.yaml
  - kre/application.yaml
