apiVersion: v1
kind: Pod
metadata:
  name: insecure-hostpath-root
spec:
  containers:
  - name: app
    image: nginx
    volumeMounts:
    - mountPath: /host
      name: host-root
  volumes:
  - name: host-root
    hostPath:
      path: /

