apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-secret-env
spec:
  validationFailureAction: Enforce
  background: true

  rules:
    - name: block-secret-env

      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - hardened

      validate:
        message: "Secret environment variables are not permitted."

        foreach:

          - list: "request.object.spec.containers"

            deny:

              conditions:

                any:

                  - key: "{{ element.env[].valueFrom.secretKeyRef || '' }}"
                    operator: NotEquals
                    value: ""