apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - integrity/verify-signed-images.yaml
  - secrets/disallow-plain-secret.yaml
  - secrets/disallow-secret-env.yaml
  - secrets/require-external-secret-store.yaml
  - secrets/require-sealed-secret.yaml
  - secrets/restrict-secret-volume.yaml