apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - verify-signed-images.yaml
  - disallow-plain-secret.yaml
  - disallow-secret-env.yaml
  - require-external-secret-store.yaml
  - require-sealed-secret.yaml
  - restrict-secret-volume.yaml
  - restrict-configmap.yaml