apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-secret-volume
spec:
  validationFailureAction: Enforce
  background: true

  rules:
    - name: validate-secret-volumes

      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - hardened

      validate:

        message: "Secret volumes must be mounted readOnly."

        foreach:

          - list: "request.object.spec.volumes"

            preconditions:

              all:

                - key: "{{ element.secret }}"
                  operator: NotEquals
                  value: null

            deny:

              conditions:

                any:

                  - key: "{{ element.secret.optional || \"\" }}"
                    operator: Equals
                    value: true