apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-secret-volume

spec:
  validationFailureAction: Enforce
  background: true

  rules:
    - name: validate-secret-volumes

      match:
        any:
          - resources:
              kinds:
                - Pod

      namespaceSelector:
        matchLabels:
          security-level: hardened

      validate:
        message: "Secret volumes must not be optional."

        foreach:
          - list: "request.object.spec.volumes[]"

            deny:
              conditions:
                all:

                  - key: "{{ element.secret.secretName || '' }}"
                    operator: NotEquals
                    value: ""

                  - key: "{{ element.secret.optional || false }}"
                    operator: Equals
                    value: true