apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-secret-volume

spec:
  validationFailureAction: Enforce
  background: true

  rules:
    - name: secret-volume-must-not-be-optional

      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaceSelector:
                matchLabels:
                  security-level: hardened

      validate:
        message: "Secret volumes must not be optional."

        pattern:
          spec:
            volumes:
              - =(secret):
                  optional: "false"