apiVersion: v1
kind: Pod
metadata:
  name: signed-test
  namespace: hardened
  labels:
    app: signed-test
    environment: hardened
spec:
  serviceAccountName: hardened-app-sa
  automountServiceAccountToken: false
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: k8-web-app
    image: staocube/k8-web-app:2.0
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
      capabilities:
        drop:
        - ALL
    resources:
      requests:
        cpu: "50m"
        memory: "64Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"