apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-signed-images
spec:
  validationFailureAction: Enforce
  background: false
  webhookTimeoutSeconds: 30
  failurePolicy: Fail
  rules:
  - name: verify-staocube-cosign-signature
    match:
      any:
      - resources:
          kinds:
          - Pod
          namespaces:
          - hardened
    verifyImages:
    - imageReferences:
      - "staocube/*"
      - "docker.io/staocube/*"
      - "index.docker.io/staocube/*"
      mutateDigest: true
      required: true
      verifyDigest: false
      attestors:
      - entries:
        - keys:
            publicKeys: |
              -----BEGIN PUBLIC KEY-----
              MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEiIpp+bPjWkHsmrs8mWDT8Zus+LYN
              a4W4EgsQNrPaPWTeGAUUef1CEWFtqsxDC4N9qLWdZi9r51IPsXR2D4H05Q==
              -----END PUBLIC KEY-----