apiVersion: v1
kind: Service
metadata:
  name: hardened-nginx-service
  namespace: hardened
  labels:
    app: hardened-nginx
    environment: hardened
spec:
  type: ClusterIP
  selector:
    app: hardened-nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP