apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-falcosidekick
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  project: default
  source:
    repoURL: https://falcosecurity.github.io/charts
    chart: falcosidekick
    targetRevision: 0.10.0
    helm:
      values: |
        webui:
          enabled: false
        config:
          debug: true
          # --- Webhook configuration to route alerts to KRE Handler ---
          webhook:
            address: "http://kre-handler.hardened.svc.cluster.local:8080/remediate"
            minimumpriority: "warning"
            checkcert: false
        service:
          type: ClusterIP
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: falco
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true