apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../k8s/baseline/namespace.yaml
  - ../../../../k8s/baseline/app-deployment.yaml
  - ../../../../k8s/baseline/app-service.yaml
  - ../../../../k8s/baseline/insecure-runtime-pod.yaml
  - ../../../../k8s/baseline/runtime-attacker-pod.yaml
  - ../../../../k8s/baseline/rbac-overprivileged.yaml