apiVersion: v1
kind: Pod
metadata:
  name: interactive-shell
  namespace: hardened
  labels:
    app: interactive-shell
    security: runtime-test
spec:
  restartPolicy: Never
  serviceAccountName: hardened-app-sa
  automountServiceAccountToken: false
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: attack
    image: busybox:1.36
    stdin: true
    tty: true
    command:
      - sh
      - -i
      - -c
      - |
        echo "[+] Spawning interactive shell session..."
        /bin/sh -i -c "whoami; id"
        sleep 300
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
      capabilities:
        drop:
          - ALL
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi