apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - trigger-outbound-connection.yaml
  - trigger-write-root.yaml
  - trigger-sensitive-files.yaml
  - trigger-terminal-shell.yaml
  - trigger-outbound-curl.yaml