apiVersion: v1
kind: Pod
metadata:
  name: privileged-runtime
  namespace: hardened
spec:
  restartPolicy: Never
  containers:
    - name: privileged
      image: alpine:3.20
      securityContext:
        privileged: true
      command:
        - sh
        - -c
        - |
          sleep 300