apiVersion: v1
kind: Pod
metadata:
  name: trigger-terminal-shell
  namespace: hardened
  labels:
    app: trigger-terminal-shell
spec:
  restartPolicy: Never
  containers:
    - name: attacker
      image: alpine:3.20
      # stdin & tty ensure a pseudo-terminal is allocated to fire terminal shell rules
      stdin: true
      tty: true
      command:
        - /bin/sh