apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-report-server
  namespace: hardened
  labels:
    app: security-report-server
    environment: hardened
spec:
  replicas: 1
  selector:
    matchLabels:
      app: security-report-server
  template:
    metadata:
      labels:
        app: security-report-server
        environment: hardened
    spec:
      serviceAccountName: hardened-app-sa
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: report-server
        image: staocube/k8s-security-report:1.0
        ports:
        - containerPort: 80
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 101
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - name: nginx-cache
          mountPath: /var/cache/nginx
        - name: nginx-run
          mountPath: /var/run
        - name: tmp
          mountPath: /tmp
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
      volumes:
      - name: nginx-cache
        emptyDir: {}
      - name: nginx-run
        emptyDir: {}
      - name: tmp
        emptyDir: {}