apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: dev-falco
  namespace: argocd

  annotations:
    argocd.argoproj.io/sync-wave: "6"

spec:
  project: default

  source:
    repoURL: https://falcosecurity.github.io/charts
    chart: falco
    targetRevision: 8.0.5

    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: falco

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true