apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-falco
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6"

spec:
  project: default

  source:
    repoURL: https://falcosecurity.github.io/charts
    chart: falco
    targetRevision: 8.0.5

    helm:
      values: |
        crds:
          enabled: true

        driver:
          enabled: true
          kind: modern_ebpf

        collectors:
          kubernetes:
            enabled: true

        serviceAccount:
          create: true

        falco:
          jsonOutput: true
          json_include_output_property: true
          json_include_output_fields_property: true
          json_include_tags_property: true

          logLevel: info
          priority: debug

          httpOutput:
            enabled: true
            url: http://dev-falcosidekick.falco.svc.cluster.local:2801

        falcosidekick:
          enabled: true
          config:
            debug: false

        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi

  destination:
    server: https://kubernetes.default.svc
    namespace: falco

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true