
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
  namespace: argocd
  finalizers:
    - argocd.argoproj.io/resources-finalizer
spec:
  project: default
  source:
    # Option A: Direct Helm Repository
    chart: falco
    repoURL: https://falcosecurity.github.io/charts
    targetRevision: 4.16.0 # Adjust to the desired chart version
    helm:
      releaseName: falco
      valueFiles:
        - '$values/gitops/platform/dev/falco/values.yaml'

    # Option B: Alternatively, point to your Git repo path if keeping values alongside
    # repoURL: https://github.com/your-org/gitops-repo.git
    # targetRevision: HEAD
    # path: apps/falco
    
  # Enable value file mapping when referencing external chart repositories
  sources:
    - repoURL: https://falcosecurity.github.io/charts
      chart: falco
      targetRevision: 4.16.0
      helm:
        valueFiles:
          - '$values/gitops/platform/dev/falco/values.yaml'
    - repoURL: https://github.com/staocubee/k8s-MSEF.git
      targetRevision: HEAD
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: falco

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true