apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - application.yaml
  - runtime-rules-configmap.yaml

patches:
  - path: daemonset-patch.yaml
    target:
      kind: DaemonSet
      name: dev-falco
      namespace: falco