apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - staocube-signed-test.yaml
  - nginx-unsigned-test.yaml
  - default-unsigned-image.yaml
  - digest-mismatch.yaml
  - wrong-attestor.yaml
  - wrong-signature.yaml