apiVersion: v1
kind: Pod
metadata:
  name: wrong-signature-test-nginx
  namespace: hardened
  labels:
    app: wrong-signature-test-nginx
    environment: hardened
spec:
  serviceAccountName: hardened-app-sa
  automountServiceAccountToken: false
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: wrong-signature-test
    image: staocube/wrong-signature-test:1.0
    ports:
    - containerPort: 80
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      runAsUser: 101
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
        - ALL
    resources:
      requests:
        cpu: "50m"
        memory: "64Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"