apiVersion: v1
kind: ConfigMap

metadata:
  name: kre-config

data:

  TARGET_RULES: |
    MSEF Host Filesystem Write Attempt
    MSEF Token and Sensitive File Access
    MSEF Cloud Metadata Server Access
    MSEF Outbound C2 Traffic
    MSEF Interactive Shell Execution