apiVersion: apps/v1
kind: Deployment
metadata:
  name: msef-kre-handler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msef-kre-handler
  template:
    metadata:
      labels:
        app: msef-kre-handler
    spec:
      serviceAccountName: msef-kre-handler

      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault

      containers:
      - name: kre
        image: staocube/msef-kre-handler:v2.0.0

        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL

        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi

        volumeMounts:
        - name: tmp
          mountPath: /tmp

      volumes:
      - name: tmp
        emptyDir: {}