apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hardened

resources:
  - serviceaccount.yaml
  - role.yaml
  - rolebinding.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml