apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: dev-external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"

spec:

  project: default

  source:

    repoURL: https://charts.external-secrets.io

    chart: external-secrets

    targetRevision: 0.18.2

    helm:

      values: |

        installCRDs: true

        serviceAccount:

          create: true

        resources:

          requests:

            cpu: 100m

            memory: 128Mi

          limits:

            cpu: 300m

            memory: 256Mi

  destination:

    server: https://kubernetes.default.svc

    namespace: external-secrets

  syncPolicy:

    automated:

      prune: true

      selfHeal: true

    syncOptions:

      - CreateNamespace=true