apiVersion: external-secrets.io/v1
kind: ClusterSecretStore

metadata:
  name: kubernetes-store

spec:

  provider:

    kubernetes:

      remoteNamespace: hardened

      server:

        url: https://kubernetes.default.svc