apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:

  name: report-server-secret

  namespace: hardened

spec:

  refreshInterval: 1h

  secretStoreRef:

    kind: ClusterSecretStore

    name: kubernetes-store

  target:

    name: report-server-secret

  data:

    - secretKey: REPORT_PASSWORD

      remoteRef:

        key: report-password