#!/usr/bin/env bash

###############################################################################
#
# Multi-Layer Security Evaluation Framework (MSEF)
#
# Metric:
#
# Runtime Response Success Rate (RRSR)
#
# RRSR = Successful Automated Responses / Runtime Attacks
#
###############################################################################

set -euo pipefail
shopt -s nullglob

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

source "$SCRIPT_DIR/lib/common.sh"
source "$SCRIPT_DIR/lib/metrics.sh"

###############################################################################
# Configuration
###############################################################################

RESULTS_DIR="${RESULTS_DIR:-$PROJECT_ROOT/results}"

JSON_DIR="$RESULTS_DIR/json"
TXT_DIR="$RESULTS_DIR/txt"
LOG_DIR="$RESULTS_DIR/logs"

mkdir -p "$JSON_DIR" "$TXT_DIR" "$LOG_DIR"

DETAILS="$LOG_DIR/rrsr-details.log"

: > "$DETAILS"

###############################################################################
# Auto-sync & KRE metrics file location
###############################################################################

METRICS_FILE="${METRICS_FILE:-$RESULTS_DIR/json/rrsr-events.jsonl}"
KRE_NAMESPACE="${KRE_NAMESPACE:-hardened}"
KRE_APP_LABEL="${KRE_APP_LABEL:-app=msef-kre-handler}"

# Auto-fetch rrsr-events.jsonl from active KRE pod if kubectl is available
if command -v kubectl &>/dev/null; then
    KRE_POD=$(kubectl get pod -n "$KRE_NAMESPACE" -l "$KRE_APP_LABEL" -o jsonpath='{.items[0].metadata.name}' 2>/dev/null || true)
    if [[ -n "$KRE_POD" ]]; then
        echo "--> Syncing metric logs from KRE Pod: $KRE_POD..."
        kubectl cp -n "$KRE_NAMESPACE" "${KRE_POD}:/data/results/rrsr-events.jsonl" "$METRICS_FILE" 2>/dev/null || true
    fi
fi

###############################################################################

banner "Runtime Response Success Rate (RRSR)"

###############################################################################

if [[ ! -f "$METRICS_FILE" ]]; then
    # Fallback check for runtime-events.jsonl if rrsr-events.jsonl does not exist
    ALT_METRICS="$RESULTS_DIR/json/runtime-events.jsonl"
    if [[ -f "$ALT_METRICS" ]]; then
        echo "WARNING: $METRICS_FILE not found. Falling back to $ALT_METRICS"
        METRICS_FILE="$ALT_METRICS"
    else
        echo "ERROR:"
        echo "$METRICS_FILE not found."
        echo
        echo "Run runtime attack simulation and ensure KRE is processing events first."
        exit 1
    fi
fi

###############################################################################

TOTAL=$(wc -l < "$METRICS_FILE")

SUCCESS=0
FAILED=0
TOTAL_LATENCY=0

###############################################################################

while read -r EVENT
do
    [[ -z "$EVENT" ]] && continue

    RULE=$(echo "$EVENT" | jq -r '.rule // "Unknown"')

    # Extract pod and namespace with fallbacks for raw Falco output_fields schema
    POD=$(echo "$EVENT" | jq -r '.pod // .output_fields["k8s.pod.name"] // "null"')
    NS=$(echo "$EVENT" | jq -r '.namespace // .output_fields["k8s.ns.name"] // "null"')

    # Extract success and latency generated by kre-handler.py
    OK=$(echo "$EVENT" | jq -r '.success // false')
    LATENCY=$(echo "$EVENT" | jq -r '.latency // 0.00')

    TOTAL_LATENCY=$(awk \
        -v a="$TOTAL_LATENCY" \
        -v b="$LATENCY" \
        'BEGIN{print a+b}')

    if [[ "$OK" == "true" ]]; then
        RESULT="SUCCESS"
        SUCCESS=$((SUCCESS+1))
    else
        RESULT="FAILED"
        FAILED=$((FAILED+1))
    fi

cat >> "$DETAILS" <<EOF
Rule      : $RULE
Namespace : $NS
Pod       : $POD
Latency   : ${LATENCY}s
Result    : $RESULT
----------------------------------------
EOF

done < "$METRICS_FILE"

###############################################################################

RRSR=$(awk \
    -v s="$SUCCESS" \
    -v t="$TOTAL" \
'BEGIN{
    if(t==0){print "0.00"; exit}
    printf "%.2f",s/t
}')

###############################################################################

AVG_LATENCY=$(awk \
    -v l="$TOTAL_LATENCY" \
    -v t="$TOTAL" \
'BEGIN{
    if(t==0){print "0.00"; exit}
    printf "%.2f",l/t
}')

###############################################################################
# JSON Output
###############################################################################

cat > "$JSON_DIR/rrsr.json" <<EOF
{
  "metric":"RRSR",
  "runtime_attacks":$TOTAL,
  "successful_responses":$SUCCESS,
  "failed_responses":$FAILED,
  "average_latency_seconds":$AVG_LATENCY,
  "score":$RRSR
}
EOF

###############################################################################
# TXT Output
###############################################################################

cat > "$TXT_DIR/rrsr.txt" <<EOF
==========================================
Runtime Response Success Rate
==========================================

Runtime Attacks

$TOTAL

Successful Responses

$SUCCESS

Failed Responses

$FAILED

Average Remediation Latency

${AVG_LATENCY} seconds

------------------------------------------

RRSR

$RRSR

Generated

$(date)

EOF

###############################################################################

cat "$TXT_DIR/rrsr.txt"