apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8srestrictsecretaccessrbac
spec:
  crd:
    spec:
      names:
        kind: K8sRestrictSecretAccessRBAC
  targets:
  - target: admission.k8s.gatekeeper.sh
    rego: |
      package k8srestrictsecretaccessrbac

      is_rbac_kind {
        input.review.kind.kind == "Role"
      }

      is_rbac_kind {
        input.review.kind.kind == "ClusterRole"
      }

      risky_secret_verb(verb) {
        verb == "get"
      }

      risky_secret_verb(verb) {
        verb == "list"
      }

      risky_secret_verb(verb) {
        verb == "watch"
      }

      risky_secret_verb(verb) {
        verb == "*"
      }

      violation[{"msg": msg}] {
        is_rbac_kind
        rule := input.review.object.rules[_]
        rule.resources[_] == "secrets"
        risky_secret_verb(rule.verbs[_])
        msg := sprintf("RBAC access to Kubernetes secrets is not allowed in %v %v", [input.review.kind.kind, input.review.object.metadata.name])
      }

      violation[{"msg": msg}] {
        is_rbac_kind
        rule := input.review.object.rules[_]
        rule.resources[_] == "*"
        risky_secret_verb(rule.verbs[_])
        msg := sprintf("Wildcard RBAC access may include secrets and is not allowed in %v %v", [input.review.kind.kind, input.review.object.metadata.name])
      }