name: Run Security Orchestrator

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - stg
          - prod

permissions:
  contents: read
  id-token: write

env:
  GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
  GCP_REGION: ${{ vars.GCP_REGION }}

jobs:
  run-security:
    name: Run Security Script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.GCP_SERVICE_ACCOUNT }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Install GKE auth plugin
        if: github.event.inputs.action != 'fmt'
        run: |
          gcloud components install gke-gcloud-auth-plugin --quiet || true
          echo "USE_GKE_GCLOUD_AUTH_PLUGIN=True" >> "$GITHUB_ENV"

      - name: Reset kubeconfig
        if: github.event.inputs.action != 'fmt'
        run: |
          rm -rf "$HOME/.kube"
          mkdir -p "$HOME/.kube"

      - name: Get GKE credentials
        if: github.event.inputs.action != 'fmt'
        continue-on-error: ${{ github.event.inputs.action == 'destroy' || github.event.inputs.action == 'destroy-plan' }}
        run: |
          gcloud container clusters get-credentials "${{ github.event.inputs.environment }}-msef-gke" \
            --region "$GCP_REGION" \
            --project "$GCP_PROJECT_ID"

      - name: Verify cluster access
        if: github.event.inputs.action != 'fmt' && github.event.inputs.action != 'destroy' && github.event.inputs.action != 'destroy-plan'
        run: |
          kubectl config current-context
          kubectl get nodes
          kubectl get ns

      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y bc

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials "${{ github.event.inputs.environment }}-msef-gke" \
            --region "$GCP_REGION" \
            --project "$GCP_PROJECT_ID"

      - name: Make scripts executable
        run: chmod +x scripts/*.sh

      - name: Run orchestrator
        run: scripts/run-k8s-security-evaluation.sh

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: security-orchestrator-${{ github.event.inputs.environment }}
          path: |
            results/